name: "RTKBase Custom"
description: "RTKBase mit TCP-angebundenem GNSS-Empfaenger"
version: "1.1.0"
slug: "rtkbase_custom"
init: false
arch:
  - amd64
options:
  virtual_com_port_enabled: true
  virtual_com_port_ip: ""
  virtual_com_port_port: 6638
schema:
  virtual_com_port_enabled: bool
  virtual_com_port_ip: str
  virtual_com_port_port: port
ports:
  80/tcp: 16080
  2101/tcp: 2101
uart: false
map:
  - share:rw
